name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.13.11-alpine3.10
    steps:
      - name: Install pre-requisites (1)
        run: |
          apk add --no-cache make jq zip curl git npm libc6-compat
      - name: Install pre-requisites (2)
        run: |
          curl -sSLO https://github.com/sgreben/subst/releases/download/1.1.1/subst_1.1.1_linux_x86_64.zip
          unzip subst_1.1.1_linux_x86_64.zip
          mv subst /usr/local/bin
      - name: Install pre-requisites (3)
        run: |
          curl -sL "https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz" | tar xz hub-linux-amd64-2.14.2/bin/hub;
          mv hub-linux-amd64-2.14.2/bin/hub /usr/local/bin
      - name: Check pre-requisites
        run: |
          which subst;
          hub --help;
      - name: Checkout
        uses: actions/checkout@master
      - run: git config user.name "GitHub Actions" && git config user.email "actions@users.noreply.github.com"
      - name: Build
        run: make binaries
      - name: Release (1)
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release (2)
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          npm version patch
          git add package.json
          git commit -am "Bump version" || true
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
