# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: git config user.name "GitHub Actions" && git config user.email "actions@users.noreply.github.com"
      - name: Build
        run: go build
      - name: Test
        run: go test ./...
